import { Store } from "./StoreList";

export const DUMMY_STORES: Store[] = [
  {
    id: "1",
    name: "PÃO DE AÇÚCAR - MARQUES DE ABRANTES",
    image: "https://placehold.co/300x200",
    rating: 4.8,
    reviews: 142,
    distance: "1.5km",
    address: "Rua Marques de Abrantes, 165",
    availableUntil: "20:00",
  },
  {
    id: "2",
    name: "CARREFOUR EXPRESS - IPANEMA",
    image: "https://placehold.co/300x200",
    rating: 4.5,
    reviews: 98,
    distance: "2.3km",
    address: "Rua Visconde de Pirajá, 123",
    availableUntil: "22:00",
  },
  {
    id: "3",
    name: "MERCADO LOCAL - LEBLON",
    image: "https://placehold.co/300x200",
    rating: 4.3,
    reviews: 76,
    distance: "3.1km",
    address: "Avenida Ataulfo de Paiva, 45",
    availableUntil: "21:00",
  },
  {
    id: "4",
    name: "SUPERMERCADO ECONÔMICO - COPACABANA",
    image: "https://placehold.co/300x200",
    rating: 4.7,
    reviews: 120,
    distance: "1.2km",
    address: "Rua Barata Ribeiro, 200",
    availableUntil: "23:00",
  },
  {
    id: "5",
    name: "ZONA SUL - BOTAFOGO",
    image: "https://placehold.co/300x200",
    rating: 4.6,
    reviews: 150,
    distance: "0.8km",
    address: "Praia de Botafogo, 300",
    availableUntil: "21:30",
  },
  {
    id: "6",
    name: "HIPERMERCADO EXTRA - FLAMENGO",
    image: "https://placehold.co/300x200",
    rating: 4.2,
    reviews: 88,
    distance: "2.0km",
    address: "Rua Senador Vergueiro, 100",
    availableUntil: "22:30",
  },
  {
    id: "7",
    name: "VERDEMAR - GÁVEA",
    image: "https://placehold.co/300x200",
    rating: 4.9,
    reviews: 167,
    distance: "4.0km",
    address: "Rua Marquês de São Vicente, 52",
    availableUntil: "19:00",
  },
  {
    id: "8",
    name: "PÃO DE AÇÚCAR - LARGO DO MACHADO",
    image: "https://placehold.co/300x200",
    rating: 4.4,
    reviews: 102,
    distance: "1.7km",
    address: "Praça Largo do Machado, 10",
    availableUntil: "20:00",
  },
  {
    id: "9",
    name: "MERCADINHO TROPICAL - SANTA TERESA",
    image: "https://placehold.co/300x200",
    rating: 4.0,
    reviews: 54,
    distance: "5.5km",
    address: "Rua Almirante Alexandrino, 400",
    availableUntil: "18:30",
  },
  {
    id: "10",
    name: "SUPERMARKET - CENTRO",
    image: "https://placehold.co/300x200",
    rating: 3.8,
    reviews: 45,
    distance: "6.0km",
    address: "Avenida Rio Branco, 150",
    availableUntil: "19:00",
  },
];
